apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-datasources
  namespace: aegis
data:
  datasources.yaml: |
    apiVersion: 1
    datasources:
      - name: Prometheus
        type: prometheus
        access: proxy
        url: http://prometheus-service.aegis.svc:9090
        isDefault: true
        jsonData:
          timeInterval: 5s
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana
  namespace: aegis
  labels:
    app: grafana
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grafana
  template:
    metadata:
      labels:
        app: grafana
    spec:
      containers:
        - name: grafana
          image: grafana/grafana:10.4.0
          env:
            - name: GF_SECURITY_ADMIN_USER
              value: "admin"
            - name: GF_SECURITY_ADMIN_PASSWORD
              value: "aegispass"
            - name: GF_USERS_ALLOW_SIGN_UP
              value: "false"
          ports:
            - containerPort: 3000
              name: web
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 250m
              memory: 256Mi
          volumeMounts:
            - name: datasources-volume
              mountPath: /etc/grafana/provisioning/datasources
      volumes:
        - name: datasources-volume
          configMap:
            name: grafana-datasources
---
apiVersion: v1
kind: Service
metadata:
  name: grafana-service
  namespace: aegis
spec:
  type: ClusterIP
  selector:
    app: grafana
  ports:
    - name: web
      port: 3000
      targetPort: 3000
