apiVersion: v1
kind: Secret
metadata:
  name: aegis-secret
  namespace: aegis
  labels:
    app.kubernetes.io/name: aegis-api
    app.kubernetes.io/part-of: aegis
type: Opaque
stringData:
  DATABASE_URL: "postgresql://aegis_user:supersecretpassword@aegis-db:5432/aegis_prod"
  API_KEY: "aegis-prod-api-key-998877"
